APP_NAME: Bridges in Wroclaw
SECRET_KEY: SECRET
BLOG_PREFIX: "/blog"
DB:
  TYPE: json_file
  PATH: examples/e2e_test_data.json

LANGUAGES:
  en:
    name: English
    flag: gb
    country: GB
  pl:
    name: polski
    flag: pl
    country: PL

FEATURE_FLAGS:
  USE_LAZY_LOADING: True
  USE_SERVER_SIDE_CLUSTERING: False
  SHOW_ACCESSIBILITY_TABLE: True
  FAKE_LOGIN: False
  CATEGORIES_HELP: True
  SHOW_SEARCH_BAR: True
  SHOW_SUGGEST_NEW_POINT_BUTTON: True

GOODMAP_FRONTEND_LIB_URL: "https://cdn.jsdelivr.net/npm/@problematy/goodmap@1.0.4"
