name: Post E2E Test Results

on:
  workflow_run:
    workflows: ["Testing pipeline"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  post-results:
    uses: problematy/goodmap-e2e-tests/.github/workflows/pr-comment.yml@d8c9fff038dc7109c28471457f28adf6730edb63
    with:
      run_id: ${{ github.event.workflow_run.id }}
    secrets:
      comment_token: ${{ secrets.GITHUB_TOKEN }}

